[package]
name = "hc_zome_notifications_coordinator"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "hc_zome_notifications_coordinator"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

notifications_integrity = { path = "../../integrity/notifications", package = "hc_zome_notifications_integrity" }

zome_utils.workspace = true
